# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:

    branches:
      - '*'

  pull_request:
    branches: [ "main" ]

jobs:

  homework2:
      runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Install dependencies
      run: dotnet restore
      working-directory: Homework2
    - name: Build
      run: dotnet build --no-restore
      working-directory: Homework2
    - name: Test
      run: dotnet test --no-build --verbosity normal
      working-directory: Homework2

  homework1:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Install dependencies
      run: dotnet restore
      working-directory: Homework1
    - name: Build
      run: dotnet build --no-restore
      working-directory: Homework1
    - name: Test
      run: dotnet test --no-build --verbosity normal
      working-directory: Homework1